# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: true

notifications:
  email:
    on_success: change
    on_failure: change
warnings_are_errors: true
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=0
